version: "3.1"

services:

  cycloblog:
    image: cycloblog:1
    restart: always
    container_name: cycloblog-1
    depends_on:
      - mysql
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql-1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_db
   

